config/routes.rb
Bookstore::Application.routes.draw do

  resources :books,   :only => [:index, :show]
  resources :authors, :only => [:index]

  root 'books#index'

end

app/models/book.rb
class Book < ActiveYaml::Base
  set_root_path Rails.root.join('config')
  set_filename 'books'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def index
		@books = Book.all
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @books = Book.all

    respond_to do |format|
      format.html
      format.yaml { render text:@books.to_yaml }
      format.json { render text:@books.to_json }
    end
  end

  def show
    @book  = Book.find(params[:id])

    respond_to do |format|
      format.html
      format.yaml { render text:@book.to_yaml }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/authors/index.html.erb
<% @books.each do|book| %>
<p><%= book.author %>
<%= link_to book.title, book %></p>
<% end %>

<%= render 'layouts/footer' %>

app/views/books/index.html.erb
<table>
  <tr>
    <th></th>
    <th>Author</th>
    <th>Title</th>
    <th></th>
  </tr>
 
  <% @books.each do |book| %>
    <tr class=<%= cycle("odd", "even") %>>
      <td><%= book.id %></td>
      <td><%= book.author %></td>
      <td><%= book.title %></td>
      <td><%= link_to book.text.truncate_by_word(10, " ...").quote, book %></td>
    </tr>
  <% end %>

<%= render 'layouts/footer' %>

app/views/books/show.html.erb
<h1><%= @book.title %></h1>

<p><%= @book.text %></p>

<%= render 'layouts/footer' %>

app/views/layouts/_footer.html.erb
</table>
<footer> 
  <table>
    <tr>
      <td class="foot-first"><%= link_to 'Books table', books_path %></td>
      <td class="foot-last"><%= link_to 'Authors', authors_path %></td>
    </tr>
  </table>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>